#! /usr/bin/env python
import argparse
import os
import sys
from decentlog import listen_channel_output


def _main():
    parser = argparse.ArgumentParser(description="Decentralized logging using dweet server")
    parser.add_argument(
        "--mode",
        type=str,
        default='LISTENER',
        help="To start program in PUBLISHER or LISTENER mode"
    )
    parser.add_argument(
        "--channel",
        type=str,
        help="Channel name where you want log to listen",
        required=True
    )

    args = parser.parse_args()
    assert args.channel, "Channel name should not be empty"
    try:
        for res in listen_channel_output(args.channel, longpoll=False):
            print(res)
    except KeyboardInterrupt:
        print("Closing .....")


if __name__ == "__main__":
    _main()
